# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='description',
            field=models.TextField(max_length=1200),
        ),
    ]
