# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 14:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20160706_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
