# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20160706_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
